import { FoodProduct } from './types';

export const FOOD_DATABASE: FoodProduct[] = [
  // --- Meat & Fish ---
  {
    id: "5941002001015", // Barcode
    name: "Piept de pui dezosat (Chicken Breast)",
    brand: "Cămara Noastră",
    store: "Lidl",
    price: 24.99,
    weight: "1kg",
    protein: 23,
    carbs: 0,
    fat: 1.5,
    calories: 110,
    fiber: 0,
    sugar: 0,
    sodium: 0.06,
    ingredients: "100% piept de pui dezosat",
    nutritionLabel: "High protein, extremely low fat. Fresh Romanian chicken.",
    costPerProteinGram: 24.99 / 230, // 230g protein per 1kg
    costPerCalorie: 24.99 / 1100,
    healthScore: 95,
    image: "🍗",
    alternatives: ["Piept de curcan (Turkey Breast)", "Tofu Clasic (Classic Tofu)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001022",
    name: "Piept de curcan (Turkey Breast)",
    brand: "Sabin",
    store: "Kaufland",
    price: 32.50,
    weight: "1kg",
    protein: 24,
    carbs: 0.1,
    fat: 1.1,
    calories: 104,
    fiber: 0,
    sugar: 0,
    sodium: 0.05,
    ingredients: "100% piept de curcan",
    nutritionLabel: "Premium lean protein source. Ideal for calorie-restricted diets.",
    costPerProteinGram: 32.50 / 240,
    costPerCalorie: 32.50 / 1040,
    healthScore: 98,
    image: "🦃",
    alternatives: ["Piept de pui dezosat (Chicken Breast)", "Tofu Clasic (Classic Tofu)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001039",
    name: "File de somon proaspăt (Fresh Salmon)",
    brand: "Ocean Fish",
    store: "Carrefour",
    price: 49.90,
    weight: "500g",
    protein: 20,
    carbs: 0,
    fat: 13,
    calories: 208,
    fiber: 0,
    sugar: 0,
    sodium: 0.05,
    ingredients: "Somon de Atlantic (Salmo salar)",
    nutritionLabel: "Rich in Omega-3 fatty acids and highly bioavailable protein.",
    costPerProteinGram: 49.90 / 100, // 100g protein in 500g
    costPerCalorie: 49.90 / 1040,
    healthScore: 90,
    image: "🐟",
    alternatives: ["Conservă de ton (Canned Tuna)", "Macrou afumat (Smoked Mackerel)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001046",
    name: "Conservă de ton în suc propriu (Canned Tuna)",
    brand: "Nixe",
    store: "Lidl",
    price: 6.49,
    weight: "160g",
    protein: 25,
    carbs: 0,
    fat: 0.5,
    calories: 105,
    fiber: 0,
    sugar: 0,
    sodium: 0.4,
    ingredients: "Tonal (Katsuwonus pelamis), apă, sare",
    nutritionLabel: "Very budget-friendly lean protein. Highly durable.",
    costPerProteinGram: 6.49 / (25 * 1.6), // ~40g protein
    costPerCalorie: 6.49 / (105 * 1.6),
    healthScore: 88,
    image: "🥫",
    alternatives: ["Sardine în ulei (Sardines in Oil)", "Piept de pui dezosat (Chicken Breast)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001053",
    name: "Pulpe de pui dezosate (Chicken Thighs)",
    brand: "CocoRico",
    store: "Auchan",
    price: 18.99,
    weight: "1kg",
    protein: 19,
    carbs: 0,
    fat: 8,
    calories: 150,
    fiber: 0,
    sugar: 0,
    sodium: 0.08,
    ingredients: "Pulpe de pui superioare dezosate, fără piele",
    nutritionLabel: "Juicy, affordable chicken option. Slightly higher fats.",
    costPerProteinGram: 18.99 / 190,
    costPerCalorie: 18.99 / 1500,
    healthScore: 85,
    image: "🍗",
    alternatives: ["Piept de pui dezosat (Chicken Breast)", "Pulpe de curcan (Turkey Thighs)"],
    category: "Meat & Fish"
  },

  // --- Dairy, Tofu & Eggs ---
  {
    id: "5941002002012",
    name: "Ouă proaspete M 30 bucăți (30 Eggs)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 19.99,
    weight: "1.5kg",
    protein: 12.5,
    carbs: 0.7,
    fat: 9.5,
    calories: 143,
    fiber: 0,
    sugar: 0.1,
    sodium: 0.13,
    ingredients: "Ouă de găină, categoria M, crescute la sol",
    nutritionLabel: "Gold-standard protein bioavailability. Perfect budget muscle food.",
    costPerProteinGram: 19.99 / (12.5 * 15), // ~187.5g protein
    costPerCalorie: 19.99 / (143 * 15),
    healthScore: 92,
    image: "🥚",
    alternatives: ["Albuș de ou la bidon (Liquid Egg Whites)", "Greek Yogurt 2%"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002029",
    name: "Iaurt grecesc 10% grăsime (Greek Yogurt 10%)",
    brand: "Pilos",
    store: "Lidl",
    price: 5.99,
    weight: "400g",
    protein: 6.0,
    carbs: 3.5,
    fat: 10.0,
    calories: 128,
    fiber: 0,
    sugar: 3.5,
    sodium: 0.05,
    ingredients: "Lapte de vacă pasteurizat, smântână, culturi de iaurt",
    nutritionLabel: "Thick, creamy yogurt rich in calcium and fats. High satiety.",
    costPerProteinGram: 5.99 / (6 * 4), // 24g protein
    costPerCalorie: 5.99 / (128 * 4),
    healthScore: 78,
    image: "🥛",
    alternatives: ["Iaurt grecesc 2% grăsime (Greek Yogurt 2%)", "Sana 3.5% (Kefir)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002036",
    name: "Iaurt grecesc 2% grăsime (Greek Yogurt 2%)",
    brand: "Pilos",
    store: "Lidl",
    price: 5.49,
    weight: "400g",
    protein: 9.0,
    carbs: 4.0,
    fat: 2.0,
    calories: 70,
    fiber: 0,
    sugar: 4.0,
    sodium: 0.05,
    ingredients: "Lapte pasteurizat semi-degresat, culturi lactice",
    nutritionLabel: "High protein yogurt with very low fat. Excellent for diets.",
    costPerProteinGram: 5.49 / (9 * 4), // 36g protein
    costPerCalorie: 5.49 / (70 * 4),
    healthScore: 94,
    image: "🥛",
    alternatives: ["Iaurt grecesc 10% grăsime (Greek Yogurt 10%)", "Brânză Făgăraș (Cottage Cheese)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002043",
    name: "Brânză proaspătă de vaci (Cottage Cheese)",
    brand: "Covalact de Țară",
    store: "Carrefour",
    price: 8.90,
    weight: "250g",
    protein: 13,
    carbs: 2.5,
    fat: 4.0,
    calories: 98,
    fiber: 0,
    sugar: 2.5,
    sodium: 0.1,
    ingredients: "Lapte de vacă pasteurizat, culturi lactice selecționate",
    nutritionLabel: "Slow-digesting casein protein. Great before sleep.",
    costPerProteinGram: 8.90 / (13 * 2.5), // 32.5g protein
    costPerCalorie: 8.90 / (98 * 2.5),
    healthScore: 90,
    image: "🧀",
    alternatives: ["Urda dulce (Sweet Whey Cheese)", "Tofu Clasic (Classic Tofu)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002050",
    name: "Tofu Clasic în saramură (Classic Tofu)",
    brand: "Inedit",
    store: "Auchan",
    price: 7.20,
    weight: "300g",
    protein: 12,
    carbs: 1.5,
    fat: 6.0,
    calories: 108,
    fiber: 1.2,
    sugar: 0.5,
    sodium: 0.8,
    ingredients: "Boabe de soia (nemodificată genetic), apă, coagulant (clorură de magneziu), sare",
    nutritionLabel: "Excellent plant-based protein source. Cholesterol-free.",
    costPerProteinGram: 7.20 / (12 * 3), // 36g protein
    costPerCalorie: 7.20 / (108 * 3),
    healthScore: 89,
    image: "⬜",
    alternatives: ["Brânză proaspătă de vaci (Cottage Cheese)", "Năut conservă (Canned Chickpeas)"],
    category: "Dairy & Eggs"
  },

  // --- Carbs, Grains & Legumes ---
  {
    id: "5941002003019",
    name: "Fulgi de ovăz clasici (Rolled Oats)",
    brand: "Crownfield",
    store: "Lidl",
    price: 3.49,
    weight: "500g",
    protein: 13.5,
    carbs: 58.7,
    fat: 7.0,
    calories: 372,
    fiber: 10.0,
    sugar: 1.0,
    sodium: 0.01,
    ingredients: "100% ovăz integral",
    nutritionLabel: "Complex carbs rich in beta-glucans. Incredible energy and fiber.",
    costPerProteinGram: 3.49 / (13.5 * 5),
    costPerCalorie: 3.49 / (372 * 5),
    healthScore: 98,
    image: "🥣",
    alternatives: ["Orez brun (Brown Rice)", "Hrișcă (Buckwheat)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003026",
    name: "Orez Basmati (Basmati Rice)",
    brand: "Uncle Ben's",
    store: "Carrefour",
    price: 12.90,
    weight: "1kg",
    protein: 8.5,
    carbs: 77,
    fat: 0.8,
    calories: 350,
    fiber: 1.5,
    sugar: 0.1,
    sodium: 0.01,
    ingredients: "Orez Basmati decorticat",
    nutritionLabel: "Fragrant, clean digesting carbohydrate. Low glycemic index.",
    costPerProteinGram: 12.90 / 85,
    costPerCalorie: 12.90 / 3500,
    healthScore: 82,
    image: "🌾",
    alternatives: ["Orez brun integral (Whole Grain Brown Rice)", "Cartofi dulci (Sweet Potatoes)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003033",
    name: "Pâine integrală feliată (Whole Wheat Bread)",
    brand: "Vel Pitar",
    store: "Kaufland",
    price: 4.80,
    weight: "500g",
    protein: 10.5,
    carbs: 41,
    fat: 1.8,
    calories: 232,
    fiber: 7.5,
    sugar: 2.2,
    sodium: 0.45,
    ingredients: "Făină integrală de grâu, apă, drojdie, sare, gluten",
    nutritionLabel: "High-fiber whole wheat bread. Provides steady insulin release.",
    costPerProteinGram: 4.80 / (10.5 * 5),
    costPerCalorie: 4.80 / (232 * 5),
    healthScore: 88,
    image: "🍞",
    alternatives: ["Pâine secară (Rye Bread)", "Orez puffed cakes (Puffed Rice Cakes)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003040",
    name: "Paste integrale Penne (Whole Wheat Pasta)",
    brand: "Combino",
    store: "Lidl",
    price: 3.99,
    weight: "500g",
    protein: 13,
    carbs: 65,
    fat: 2.0,
    calories: 345,
    fiber: 8.0,
    sugar: 3.0,
    sodium: 0.01,
    ingredients: "Griș din grâu dur integral, apă",
    nutritionLabel: "High fiber dur-wheat pasta. Excellent budget endurance carb.",
    costPerProteinGram: 3.99 / (13 * 5),
    costPerCalorie: 3.99 / (345 * 5),
    healthScore: 92,
    image: "🍝",
    alternatives: ["Paste de năut (Chickpea Pasta)", "Orez Basmati (Basmati Rice)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003057",
    name: "Fasole roșie conservă (Canned Red Beans)",
    brand: "Freshona",
    store: "Lidl",
    price: 3.29,
    weight: "400g",
    protein: 8.1,
    carbs: 15.5,
    fat: 0.6,
    calories: 108,
    fiber: 6.8,
    sugar: 0.8,
    sodium: 0.35,
    ingredients: "Fasole roșie Kidney, apă, sare",
    nutritionLabel: "Cheap, high-fiber plant-based source. Very filling.",
    costPerProteinGram: 3.29 / (8.1 * 4),
    costPerCalorie: 3.29 / (108 * 4),
    healthScore: 91,
    image: "🥫",
    alternatives: ["Năut conservă (Canned Chickpeas)", "Linte verde proaspătă (Fresh Green Lentils)"],
    category: "Carbs & Grains"
  },

  // --- Vegetables & Fruits ---
  {
    id: "5941002004016",
    name: "Amestec de legume congelate (Frozen Veggies)",
    brand: "Hortex",
    store: "Auchan",
    price: 7.99,
    weight: "450g",
    protein: 2.5,
    carbs: 6.8,
    fat: 0.3,
    calories: 45,
    fiber: 3.2,
    sugar: 2.5,
    sodium: 0.03,
    ingredients: "Mazăre, morcovi, porumb, fasole verde, conopidă",
    nutritionLabel: "Essential micronutrients. Extremely long storage life. Budget hack.",
    costPerProteinGram: 7.99 / (2.5 * 4.5),
    costPerCalorie: 7.99 / (45 * 4.5),
    healthScore: 95,
    image: "🥦",
    alternatives: ["Spanac tocat congelat (Frozen Chopped Spinach)", "Broccoli proaspăt (Fresh Broccoli)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004023",
    name: "Banane proaspete (Fresh Bananas)",
    brand: "Chiquita",
    store: "Metro",
    price: 6.99,
    weight: "1kg",
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    calories: 89,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 0.01,
    ingredients: "Banane proaspete importate",
    nutritionLabel: "Excellent workout energy. Contains potassium and simple sugars.",
    costPerProteinGram: 6.99 / 11,
    costPerCalorie: 6.99 / 890,
    healthScore: 84,
    image: "🍌",
    alternatives: ["Mere roșii proaspete (Fresh Red Apples)", "Afine proaspete (Fresh Blueberries)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004030",
    name: "Broccoli proaspăt (Fresh Broccoli)",
    brand: "Delhaize",
    store: "Mega Image",
    price: 8.50,
    weight: "500g",
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    calories: 34,
    fiber: 2.6,
    sugar: 1.7,
    sodium: 0.03,
    ingredients: "100% Broccoli",
    nutritionLabel: "Powerhouse of Vitamin C, K and Sulforaphane. Immune system support.",
    costPerProteinGram: 8.50 / (2.8 * 5),
    costPerCalorie: 8.50 / (34 * 5),
    healthScore: 99,
    image: "🥦",
    alternatives: ["Amestec de legume congelate (Frozen Veggies)", "Spanac proaspăt (Fresh Spinach)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004047",
    name: "Fructe de pădure congelate (Frozen Berries)",
    brand: "Green Grocer",
    store: "Lidl",
    price: 11.99,
    weight: "750g",
    protein: 1.0,
    carbs: 7.5,
    fat: 0.5,
    calories: 43,
    fiber: 4.8,
    sugar: 6.0,
    sodium: 0.01,
    ingredients: "Mure, zmeură, coacăze roșii, afine",
    nutritionLabel: "Extremely high in antioxidants. Perfect low-calorie yogurt topping.",
    costPerProteinGram: 11.99 / 7.5,
    costPerCalorie: 11.99 / (43 * 7.5),
    healthScore: 96,
    image: "🍓",
    alternatives: ["Mere roșii proaspete (Fresh Red Apples)", "Banane proaspete (Fresh Bananas)"],
    category: "Veg & Fruit"
  },

  // --- Fats, Nuts & Supplements ---
  {
    id: "5941002005013",
    name: "Unt de arahide cremos (Peanut Butter)",
    brand: "Mcennedy",
    store: "Lidl",
    price: 9.99,
    weight: "450g",
    protein: 24.4,
    carbs: 12.0,
    fat: 51.3,
    calories: 620,
    fiber: 6.0,
    sugar: 6.4,
    sodium: 0.4,
    ingredients: "Arahide prăjite (95%), ulei de palmier, zahăr, sare",
    nutritionLabel: "High calorie density, cheap healthy fats and moderate protein.",
    costPerProteinGram: 9.99 / (24.4 * 4.5), // ~110g protein
    costPerCalorie: 9.99 / (620 * 4.5),
    healthScore: 75,
    image: "🥜",
    alternatives: ["Migdale crude (Raw Almonds)", "Ulei de măsline extravirgin (Extra Virgin Olive Oil)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002005020",
    name: "Migdale crude (Raw Almonds)",
    brand: "Bellarom",
    store: "Lidl",
    price: 13.49,
    weight: "200g",
    protein: 21.1,
    carbs: 9.1,
    fat: 50.0,
    calories: 579,
    fiber: 12.5,
    sugar: 4.3,
    sodium: 0.01,
    ingredients: "100% migdale crude decojite",
    nutritionLabel: "Rich in vitamin E and monounsaturated fats. Excellent brain food.",
    costPerProteinGram: 13.49 / (21.1 * 2),
    costPerCalorie: 13.49 / (579 * 2),
    healthScore: 92,
    image: "🥜",
    alternatives: ["Unt de arahide cremos (Peanut Butter)", "Ulei de măsline extravirgin (Extra Virgin Olive Oil)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002005037",
    name: "Whey Protein Concentrate 80%",
    brand: "Myprotein",
    store: "Metro",
    price: 119.00,
    weight: "1kg",
    protein: 80,
    carbs: 6.0,
    fat: 7.0,
    calories: 412,
    fiber: 0,
    sugar: 4.0,
    sodium: 0.15,
    ingredients: "Concentrat proteic din zer (lapte), emulgator (lecitină de soia)",
    nutritionLabel: "Ultra-pure fast digesting protein. Highest protein-to-cost ratio for gym-goers.",
    costPerProteinGram: 119.00 / 800, // 800g protein
    costPerCalorie: 119.00 / 4120,
    healthScore: 89,
    image: "🥤",
    alternatives: ["Ouă proaspete M 30 bucăți (30 Eggs)", "Iaurt grecesc 2% grăsime (Greek Yogurt 2%)"],
    category: "Supplements"
  },
  {
    id: "5941002005044",
    name: "Ulei de măsline extravirgin (Extra Virgin Olive Oil)",
    brand: "Primadonna",
    store: "Lidl",
    price: 29.99,
    weight: "750ml",
    protein: 0,
    carbs: 0,
    fat: 91,
    calories: 824,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    ingredients: "100% ulei de măsline extravirgin obținut prin presare la rece",
    nutritionLabel: "Heart-healthy fats, essential for hormone production and general health.",
    costPerProteinGram: 999, // infinite
    costPerCalorie: 29.99 / (824 * 7.5),
    healthScore: 95,
    image: "🫒",
    alternatives: ["Unt de arahide cremos (Peanut Butter)", "Migdale crude (Raw Almonds)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002003064",
    name: "Lentile verzi uscate (Green Lentils)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 6.99,
    weight: "500g",
    protein: 24,
    carbs: 50,
    fat: 1.5,
    calories: 310,
    fiber: 11.5,
    sugar: 1.5,
    sodium: 0.01,
    ingredients: "100% lentile verzi uscate",
    nutritionLabel: "Excellent source of high-fiber plant protein and slow-burning carbs.",
    costPerProteinGram: 6.99 / 120,
    costPerCalorie: 6.99 / 1550,
    healthScore: 96,
    image: "🧆",
    alternatives: ["Fasole roșie conservă (Canned Red Beans)", "Năut conservă (Canned Chickpeas)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002004054",
    name: "Spanac tocat congelat (Frozen Spinach)",
    brand: "Freshona",
    store: "Lidl",
    price: 4.49,
    weight: "400g",
    protein: 2.9,
    carbs: 2.1,
    fat: 0.4,
    calories: 23,
    fiber: 2.4,
    sugar: 0.5,
    sodium: 0.05,
    ingredients: "100% spanac congelat",
    nutritionLabel: "Superfood rich in iron, lutein, and magnesium. Very low in calories.",
    costPerProteinGram: 4.49 / 11.6,
    costPerCalorie: 4.49 / 92,
    healthScore: 98,
    image: "🥬",
    alternatives: ["Broccoli proaspăt (Fresh Broccoli)", "Amestec de legume congelate (Frozen Veggies)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002003071",
    name: "Cartofi dulci proaspeți (Sweet Potatoes)",
    brand: "Delhaize",
    store: "Mega Image",
    price: 8.99,
    weight: "1kg",
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    calories: 86,
    fiber: 3.0,
    sugar: 4.2,
    sodium: 0.05,
    ingredients: "Cartofi dulci intregi proaspeți",
    nutritionLabel: "Nutrient-dense carbohydrate rich in Vitamin A and dietary fibers.",
    costPerProteinGram: 8.99 / 16,
    costPerCalorie: 8.99 / 860,
    healthScore: 91,
    image: "🍠",
    alternatives: ["Orez Basmati (Basmati Rice)", "Fulgi de ovăz clasici (Rolled Oats)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003088",
    name: "Năut în saramură conservă (Canned Chickpeas)",
    brand: "Freshona",
    store: "Lidl",
    price: 3.49,
    weight: "400g",
    protein: 7.0,
    carbs: 16.0,
    fat: 1.8,
    calories: 120,
    fiber: 4.5,
    sugar: 0.8,
    sodium: 0.38,
    ingredients: "Năut boabe, apă, sare",
    nutritionLabel: "Versatile plant-based carb and protein. Perfect for hummus or salads.",
    costPerProteinGram: 3.49 / 28,
    costPerCalorie: 3.49 / 480,
    healthScore: 92,
    image: "🥫",
    alternatives: ["Fasole roșie conservă (Canned Red Beans)", "Lentile verzi uscate (Green Lentils)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002005051",
    name: "Miez de nucă crud (Raw Walnuts)",
    brand: "Sabin",
    store: "Kaufland",
    price: 14.99,
    weight: "250g",
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    calories: 654,
    fiber: 6.7,
    sugar: 2.6,
    sodium: 0.01,
    ingredients: "100% miez de nucă românesc crud",
    nutritionLabel: "Elite source of plant-based Omega-3 fats (ALA). Incredible brain and heart food.",
    costPerProteinGram: 14.99 / 38,
    costPerCalorie: 14.99 / 1635,
    healthScore: 94,
    image: "🥜",
    alternatives: ["Migdale crude (Raw Almonds)", "Unt de arahide cremos (Peanut Butter)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002001060",
    name: "Sardine întregi în ulei de măsline (Canned Sardines)",
    brand: "Nixe",
    store: "Lidl",
    price: 5.99,
    weight: "125g",
    protein: 22.0,
    carbs: 0.0,
    fat: 12.0,
    calories: 196,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 0.45,
    ingredients: "Sardine (Sardina pilchardus) 70%, ulei de măsline 29%, sare",
    nutritionLabel: "Incredible nutrient-dense source of calcium, vitamin D and clean protein.",
    costPerProteinGram: 5.99 / 27.5,
    costPerCalorie: 5.99 / 245,
    healthScore: 94,
    image: "🥫",
    alternatives: ["Conservă de ton în suc propriu (Canned Tuna)", "File de somon proaspăt (Fresh Salmon)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001077",
    name: "Carne tocată de vită 15% grăsime (Ground Beef)",
    brand: "Cămara Noastră",
    store: "Lidl",
    price: 18.99,
    weight: "500g",
    protein: 19,
    carbs: 0,
    fat: 15,
    calories: 211,
    fiber: 0,
    sugar: 0,
    sodium: 0.08,
    ingredients: "100% carne tocată de vită cu conținut redus de grăsime",
    nutritionLabel: "High protein beef, rich in bioavailable iron and zinc.",
    costPerProteinGram: 18.99 / (19 * 5),
    costPerCalorie: 18.99 / (211 * 5),
    healthScore: 85,
    image: "🥩",
    alternatives: ["Piept de pui dezosat (Chicken Breast)", "Cotlet de porc fără os feliat (Pork Chop)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001084",
    name: "Cotlet de porc fără os feliat (Pork Chop)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 16.50,
    weight: "650g",
    protein: 22,
    carbs: 0,
    fat: 4.5,
    calories: 129,
    fiber: 0,
    sugar: 0,
    sodium: 0.05,
    ingredients: "100% cotlet de porc feliat",
    nutritionLabel: "Lean pork chop cuts. Very low in saturated fats when trimmed.",
    costPerProteinGram: 16.50 / (22 * 6.5),
    costPerCalorie: 16.50 / (129 * 6.5),
    healthScore: 88,
    image: "🥩",
    alternatives: ["Piept de pui dezosat (Chicken Breast)", "Carne tocată de vită 15% grăsime (Ground Beef)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001091",
    name: "Șuncă de curcan feliată (Turkey Ham)",
    brand: "Dulano",
    store: "Lidl",
    price: 6.99,
    weight: "150g",
    protein: 18,
    carbs: 1.0,
    fat: 2.0,
    calories: 94,
    fiber: 0,
    sugar: 0.5,
    sodium: 0.9,
    ingredients: "Piept de curcan (85%), apă, sare, condimente",
    nutritionLabel: "Ultra-lean, high-convenience sandwich protein.",
    costPerProteinGram: 6.99 / (18 * 1.5),
    costPerCalorie: 6.99 / (94 * 1.5),
    healthScore: 82,
    image: "🥓",
    alternatives: ["Piept de pui dezosat (Chicken Breast)", "Tofu Clasic în saramură (Classic Tofu)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001107",
    name: "Creveți decorticați congelați (Frozen Shrimp)",
    brand: "Ocean Fish",
    store: "Carrefour",
    price: 29.90,
    weight: "400g",
    protein: 20,
    carbs: 0.2,
    fat: 1.0,
    calories: 91,
    fiber: 0,
    sugar: 0,
    sodium: 0.35,
    ingredients: "Creveți decorticați, apă, sare",
    nutritionLabel: "Extremely low calorie lean protein. High in iodine and selenium.",
    costPerProteinGram: 29.90 / (20 * 4),
    costPerCalorie: 29.90 / (91 * 4),
    healthScore: 92,
    image: "🍤",
    alternatives: ["File de somon proaspăt (Fresh Salmon)", "File de cod proaspăt (Fresh Cod Fillet)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002001114",
    name: "File de cod proaspăt (Fresh Cod Fillet)",
    brand: "Ocean Fish",
    store: "Auchan",
    price: 22.90,
    weight: "400g",
    protein: 18,
    carbs: 0,
    fat: 0.6,
    calories: 82,
    fiber: 0,
    sugar: 0,
    sodium: 0.08,
    ingredients: "100% file de cod de Atlantic proaspăt",
    nutritionLabel: "Super lean white fish, perfect for calorie-controlled fat loss plans.",
    costPerProteinGram: 22.90 / (18 * 4),
    costPerCalorie: 22.90 / (82 * 4),
    healthScore: 95,
    image: "🐟",
    alternatives: ["File de somon proaspăt (Fresh Salmon)", "Conservă de ton în suc propriu (Canned Tuna)"],
    category: "Meat & Fish"
  },
  {
    id: "5941002002067",
    name: "Iaurt în stil islandez Skyr 0% (Icelandic Skyr)",
    brand: "Pilos",
    store: "Lidl",
    price: 4.49,
    weight: "350g",
    protein: 11,
    carbs: 4.0,
    fat: 0.2,
    calories: 62,
    fiber: 0,
    sugar: 4.0,
    sodium: 0.06,
    ingredients: "Lapte degresat pasteurizat, culturi de Skyr",
    nutritionLabel: "Thick Icelandic yogurt with outstanding high protein density and zero fat.",
    costPerProteinGram: 4.49 / (11 * 3.5),
    costPerCalorie: 4.49 / (62 * 3.5),
    healthScore: 98,
    image: "🥛",
    alternatives: ["Iaurt grecesc 2% grăsime (Greek Yogurt 2%)", "Brânză proaspătă de vaci (Cottage Cheese)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002074",
    name: "Brânză Făgăraș light 2% (Cottage Cheese & Sourcream)",
    brand: "Covalact de Țară",
    store: "Carrefour",
    price: 5.20,
    weight: "200g",
    protein: 10,
    carbs: 3.0,
    fat: 2.0,
    calories: 70,
    fiber: 0,
    sugar: 3.0,
    sodium: 0.1,
    ingredients: "Lapte de vacă pasteurizat, smântână, culturi lactice",
    nutritionLabel: "Traditional high-protein cottage cheese mixture. Very creamy and low fat.",
    costPerProteinGram: 5.20 / (10 * 2),
    costPerCalorie: 5.20 / (70 * 2),
    healthScore: 92,
    image: "🧀",
    alternatives: ["Brânză proaspătă de vaci (Cottage Cheese)", "Iaurt în stil islandez Skyr 0% (Icelandic Skyr)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002081",
    name: "Mozzarella light feliată sau bilă (Mozzarella Light)",
    brand: "Lovilio",
    store: "Lidl",
    price: 4.99,
    weight: "125g",
    protein: 19,
    carbs: 1.5,
    fat: 9.0,
    calories: 163,
    fiber: 0,
    sugar: 1.0,
    sodium: 0.5,
    ingredients: "Lapte pasteurizat semi-degresat, sare, coagulant microbiologic",
    nutritionLabel: "High protein, calcium-rich cheese with 50% less fat than standard mozzarella.",
    costPerProteinGram: 4.99 / (19 * 1.25),
    costPerCalorie: 4.99 / (163 * 1.25),
    healthScore: 88,
    image: "🧀",
    alternatives: ["Brânză proaspătă de vaci (Cottage Cheese)", "Tofu Clasic în saramură (Classic Tofu)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002098",
    name: "Kefir proaspăt 1.5% grăsime (Kefir)",
    brand: "Covalact",
    store: "Kaufland",
    price: 3.99,
    weight: "500g",
    protein: 3.2,
    carbs: 4.1,
    fat: 1.5,
    calories: 43,
    fiber: 0,
    sugar: 4.1,
    sodium: 0.05,
    ingredients: "Lapte de vacă pasteurizat semi-degresat, culturi de kefir",
    nutritionLabel: "Rich in gut-friendly probiotics, vitamins, and high bioavailability minerals.",
    costPerProteinGram: 3.99 / (3.2 * 5),
    costPerCalorie: 3.99 / (43 * 5),
    healthScore: 96,
    image: "🥛",
    alternatives: ["Iaurt grecesc 2% grăsime (Greek Yogurt 2%)", "Lapte de vacă 1.5% grăsime (UHT Cow Milk)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002104",
    name: "Lapte de vacă 1.5% grăsime (UHT Cow Milk)",
    brand: "Pilos",
    store: "Lidl",
    price: 4.29,
    weight: "1L",
    protein: 3.2,
    carbs: 4.7,
    fat: 1.5,
    calories: 45,
    fiber: 0,
    sugar: 4.7,
    sodium: 0.05,
    ingredients: "Lapte de vacă omogenizat și pasteurizat la temperatură înaltă",
    nutritionLabel: "Standard daily milk for cooking, oatmeal base or drinking. Good calcium source.",
    costPerProteinGram: 4.29 / (3.2 * 10),
    costPerCalorie: 4.29 / (45 * 10),
    healthScore: 90,
    image: "🥛",
    alternatives: ["Băutură din migdale neîndulcită (Unsweetened Almond Milk)", "Kefir proaspăt 1.5% grăsime (Kefir)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002111",
    name: "Băutură din migdale neîndulcită (Unsweetened Almond Milk)",
    brand: "Alpro",
    store: "Carrefour",
    price: 11.50,
    weight: "1L",
    protein: 0.5,
    carbs: 0.2,
    fat: 1.1,
    calories: 13,
    fiber: 0.2,
    sugar: 0,
    sodium: 0.05,
    ingredients: "Apă, migdale (2.3%), fosfat tricalcic, sare, gume naturale",
    nutritionLabel: "Lactose-free, ultra low-calorie milk alternative. Enriched with calcium, Vit D and B12.",
    costPerProteinGram: 11.50 / (0.5 * 10),
    costPerCalorie: 11.50 / (13 * 10),
    healthScore: 91,
    image: "🥛",
    alternatives: ["Lapte de vacă 1.5% grăsime (UHT Cow Milk)", "Kefir proaspăt 1.5% grăsime (Kefir)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002002128",
    name: "Ouă proaspete mărimea L 10 bucăți (10 Large Eggs)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 8.49,
    weight: "600g",
    protein: 13,
    carbs: 0.7,
    fat: 10,
    calories: 147,
    fiber: 0,
    sugar: 0.1,
    sodium: 0.13,
    ingredients: "Zece ouă de găină proaspete, categoria L, crescute la sol",
    nutritionLabel: "Premium nutrient source. High quality fat and complete amino-acid score.",
    costPerProteinGram: 8.49 / (13 * 6),
    costPerCalorie: 8.49 / (147 * 6),
    healthScore: 92,
    image: "🥚",
    alternatives: ["Ouă proaspete M 30 bucăți (30 Eggs)", "Iaurt în stil islandez Skyr 0% (Icelandic Skyr)"],
    category: "Dairy & Eggs"
  },
  {
    id: "5941002003095",
    name: "Cartofi albi proaspeți (Fresh White Potatoes)",
    brand: "Delhaize",
    store: "Mega Image",
    price: 3.49,
    weight: "1kg",
    protein: 2.0,
    carbs: 17.5,
    fat: 0.1,
    calories: 77,
    fiber: 2.2,
    sugar: 0.8,
    sodium: 0.01,
    ingredients: "Cartofi albi proaspeți românești",
    nutritionLabel: "High satiety whole food. Excellent source of potassium and clean starch energy.",
    costPerProteinGram: 3.49 / 20,
    costPerCalorie: 3.49 / 770,
    healthScore: 85,
    image: "🥔",
    alternatives: ["Cartofi dulci proaspeți (Sweet Potatoes)", "Orez Basmati (Basmati Rice)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003101",
    name: "Orez brun integral pungi (Whole Grain Brown Rice)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 5.99,
    weight: "1kg",
    protein: 7.5,
    carbs: 72,
    fat: 1.9,
    calories: 345,
    fiber: 3.5,
    sugar: 0.4,
    sodium: 0.01,
    ingredients: "100% orez brun integral decorticat",
    nutritionLabel: "High fiber slow digestion rice. Retains bran nutrients and magnesium.",
    costPerProteinGram: 5.99 / 75,
    costPerCalorie: 5.99 / 3450,
    healthScore: 94,
    image: "🌾",
    alternatives: ["Orez Basmati (Basmati Rice)", "Hrișcă proaspătă decorticată (Raw Buckwheat)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003118",
    name: "Semințe de Quinoa albă (White Quinoa Seeds)",
    brand: "Sabin",
    store: "Carrefour",
    price: 8.90,
    weight: "250g",
    protein: 14.1,
    carbs: 57.2,
    fat: 6.0,
    calories: 368,
    fiber: 7.0,
    sugar: 1.1,
    sodium: 0.01,
    ingredients: "100% boabe de quinoa albă crude",
    nutritionLabel: "Pseudocereal containing all nine essential amino acids. High in antioxidants.",
    costPerProteinGram: 8.90 / (14.1 * 2.5),
    costPerCalorie: 8.90 / (368 * 2.5),
    healthScore: 96,
    image: "🌾",
    alternatives: ["Fulgi de ovăz clasici (Rolled Oats)", "Orez brun integral pungi (Whole Grain Brown Rice)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003125",
    name: "Rondele din orez expandat (Puffed Rice Cakes)",
    brand: "Sano Vita",
    store: "Auchan",
    price: 3.19,
    weight: "100g",
    protein: 8.0,
    carbs: 80,
    fat: 2.2,
    calories: 375,
    fiber: 3.1,
    sugar: 0.5,
    sodium: 0.1,
    ingredients: "Orez integral, sare",
    nutritionLabel: "Extremely lightweight quick digesting carb. Perfect pre-workout snack base.",
    costPerProteinGram: 3.19 / 8.0,
    costPerCalorie: 3.19 / 375,
    healthScore: 80,
    image: "🥯",
    alternatives: ["Pâine integrală feliată (Whole Wheat Bread)", "Orez Basmati (Basmati Rice)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003132",
    name: "Porumb dulce boabe conservă (Canned Sweet Corn)",
    brand: "Freshona",
    store: "Lidl",
    price: 3.49,
    weight: "340g",
    protein: 2.9,
    carbs: 15.6,
    fat: 1.2,
    calories: 86,
    fiber: 2.0,
    sugar: 4.5,
    sodium: 0.25,
    ingredients: "Boabe de porumb dulce, apă, sare",
    nutritionLabel: "Juicy, naturally sweet high-fiber addition for salads and rice mixes.",
    costPerProteinGram: 3.49 / (2.9 * 3.4),
    costPerCalorie: 3.49 / (86 * 3.4),
    healthScore: 88,
    image: "🌽",
    alternatives: ["Fasole roșie conservă (Canned Red Beans)", "Lentile verzi uscate (Green Lentils)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003149",
    name: "Hrișcă proaspătă decorticată (Raw Buckwheat)",
    brand: "Sano Vita",
    store: "Auchan",
    price: 7.99,
    weight: "500g",
    protein: 13,
    carbs: 71,
    fat: 3.4,
    calories: 343,
    fiber: 10,
    sugar: 1.5,
    sodium: 0.01,
    ingredients: "100% hrișcă decorticată crudă",
    nutritionLabel: "Mineral-rich gluten-free carbohydrate. Extremely slow release insulin response.",
    costPerProteinGram: 7.99 / (13 * 5),
    costPerCalorie: 7.99 / (343 * 5),
    healthScore: 96,
    image: "🌾",
    alternatives: ["Fulgi de ovăz clasici (Rolled Oats)", "Orez brun integral pungi (Whole Grain Brown Rice)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002003156",
    name: "Fasole albă boabe în saramură (Canned White Beans)",
    brand: "Freshona",
    store: "Lidl",
    price: 2.89,
    weight: "400g",
    protein: 6.5,
    carbs: 14.3,
    fat: 0.5,
    calories: 95,
    fiber: 6.2,
    sugar: 0.5,
    sodium: 0.32,
    ingredients: "Fasole albă boabe, apă, sare",
    nutritionLabel: "Fabulous source of cheap complex protein, prebiotic fibers, and minerals.",
    costPerProteinGram: 2.89 / (6.5 * 4),
    costPerCalorie: 2.89 / (95 * 4),
    healthScore: 91,
    image: "🥫",
    alternatives: ["Fasole roșie conservă (Canned Red Beans)", "Năut în saramură conservă (Canned Chickpeas)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002004061",
    name: "Mere roșii proaspete (Fresh Red Apples)",
    brand: "Delhaize",
    store: "Mega Image",
    price: 4.99,
    weight: "1kg",
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    calories: 52,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 0.01,
    ingredients: "100% mere roșii proaspete locale",
    nutritionLabel: "High in prebiotic pectin fibers, vitamin C and antioxidants. Great daily snack.",
    costPerProteinGram: 4.99 / 3,
    costPerCalorie: 4.99 / 520,
    healthScore: 93,
    image: "🍎",
    alternatives: ["Banane proaspete (Fresh Bananas)", "Afine proaspete caserolă (Fresh Blueberries)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004078",
    name: "Afine proaspete caserolă (Fresh Blueberries)",
    brand: "Delhaize",
    store: "Mega Image",
    price: 9.99,
    weight: "125g",
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    calories: 57,
    fiber: 2.4,
    sugar: 10.0,
    sodium: 0.01,
    ingredients: "100% afine proaspete de cultură",
    nutritionLabel: "Gold standard brain-health food. Packed with health-optimizing anthocyanins.",
    costPerProteinGram: 9.99 / (0.7 * 1.25),
    costPerCalorie: 9.99 / (57 * 1.25),
    healthScore: 100,
    image: "🫐",
    alternatives: ["Fructe de pădure congelate (Frozen Berries)", "Mere roșii proaspete (Fresh Red Apples)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002005068",
    name: "Avocado Ready-to-Eat 2 bucăți (Fresh Avocado)",
    brand: "Sabin",
    store: "Carrefour",
    price: 11.90,
    weight: "300g",
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    calories: 160,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 0.01,
    ingredients: "Avocado Hass proaspăt importat",
    nutritionLabel: "Rich in healthy monounsaturated oleic acids, fibers and critical potassium.",
    costPerProteinGram: 11.90 / (2 * 3),
    costPerCalorie: 11.90 / (160 * 3),
    healthScore: 95,
    image: "🥑",
    alternatives: ["Ulei de măsline extravirgin (Extra Virgin Olive Oil)", "Unt de arahide cremos (Peanut Butter)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002004085",
    name: "Căpșuni proaspete caserolă (Fresh Strawberries)",
    brand: "Sabin",
    store: "Kaufland",
    price: 8.99,
    weight: "500g",
    protein: 0.8,
    carbs: 7.7,
    fat: 0.3,
    calories: 32,
    fiber: 2.0,
    sugar: 4.9,
    sodium: 0.01,
    ingredients: "Căpșuni proaspete de cultură",
    nutritionLabel: "Extremely low-calorie sweet snack. Loaded with Vitamin C and water content.",
    costPerProteinGram: 8.99 / (0.8 * 5),
    costPerCalorie: 8.99 / (32 * 5),
    healthScore: 95,
    image: "🍓",
    alternatives: ["Afine proaspete caserolă (Fresh Blueberries)", "Mere roșii proaspete (Fresh Red Apples)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004092",
    name: "Castraveți proaspeți fabio (Fresh Cucumbers)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 3.49,
    weight: "500g",
    protein: 0.6,
    carbs: 3.6,
    fat: 0.1,
    calories: 15,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 0.01,
    ingredients: "100% castraveți proaspeți",
    nutritionLabel: "Ultra hydrating salad staple. Near zero calories, superb crunch.",
    costPerProteinGram: 3.49 / (0.6 * 5),
    costPerCalorie: 3.49 / (15 * 5),
    healthScore: 92,
    image: "🥒",
    alternatives: ["Roșii proaspete ciorchine (Fresh Tomatoes)", "Ardei gras / capia roșu proaspăt (Fresh Bell Pepper)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004108",
    name: "Roșii proaspete ciorchine (Fresh Tomatoes)",
    brand: "Cămara Noastră",
    store: "Lidl",
    price: 6.49,
    weight: "1kg",
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    calories: 18,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 0.01,
    ingredients: "Roșii de masă ciorchine",
    nutritionLabel: "High in heart-healthy lycopene and vitamin A. Excellent in salads.",
    costPerProteinGram: 6.49 / 9,
    costPerCalorie: 6.49 / 180,
    healthScore: 94,
    image: "🍅",
    alternatives: ["Castraveți proaspeți fabio (Fresh Cucumbers)", "Ardei gras / capia roșu proaspăt (Fresh Bell Pepper)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004115",
    name: "Ardei gras / capia roșu proaspăt (Fresh Bell Pepper)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 7.99,
    weight: "500g",
    protein: 1.0,
    carbs: 6.0,
    fat: 0.3,
    calories: 31,
    fiber: 2.1,
    sugar: 4.2,
    sodium: 0.01,
    ingredients: "Ardei gras roșu proaspăt",
    nutritionLabel: "Incredible vitamin C payload. Crunchy, sweet, and low calorie.",
    costPerProteinGram: 7.99 / (1.0 * 5),
    costPerCalorie: 7.99 / (31 * 5),
    healthScore: 96,
    image: "🫑",
    alternatives: ["Roșii proaspete ciorchine (Fresh Tomatoes)", "Castraveți proaspeți fabio (Fresh Cucumbers)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002004122",
    name: "Spanac proaspăt baby caserolă (Fresh Baby Spinach)",
    brand: "Delhaize",
    store: "Mega Image",
    price: 5.50,
    weight: "125g",
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    calories: 23,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 0.08,
    ingredients: "Spanac baby proaspăt, spălat",
    nutritionLabel: "Elite source of leafy iron, folate, and calcium. Great raw or lightly cooked.",
    costPerProteinGram: 5.50 / (2.9 * 1.25),
    costPerCalorie: 5.50 / (23 * 1.25),
    healthScore: 99,
    image: "🥬",
    alternatives: ["Spanac tocat congelat (Frozen Spinach)", "Broccoli proaspăt (Fresh Broccoli)"],
    category: "Veg & Fruit"
  },
  {
    id: "5941002003163",
    name: "Miere de albine polifloră bio (Natural Polyfloral Honey)",
    brand: "Cămara Noastră",
    store: "Lidl",
    price: 14.49,
    weight: "400g",
    protein: 0.3,
    carbs: 82,
    fat: 0,
    calories: 304,
    fiber: 0.2,
    sugar: 82,
    sodium: 0.01,
    ingredients: "100% miere polifloră naturală de albine",
    nutritionLabel: "Rich natural source of bio-enzymes, antioxidants, and quick energy.",
    costPerProteinGram: 14.49 / (0.3 * 4),
    costPerCalorie: 14.49 / (304 * 4),
    healthScore: 78,
    image: "🍯",
    alternatives: ["Unt de arahide cremos (Peanut Butter)", "Banane proaspete (Fresh Bananas)"],
    category: "Carbs & Grains"
  },
  {
    id: "5941002005075",
    name: "Humus clasic cu ulei de măsline (Classic Hummus)",
    brand: "Chef Select",
    store: "Lidl",
    price: 4.49,
    weight: "250g",
    protein: 4.8,
    carbs: 8.3,
    fat: 9.6,
    calories: 166,
    fiber: 4.0,
    sugar: 0.5,
    sodium: 0.42,
    ingredients: "Năut fiert (60%), pastă de susan tahini, ulei de măsline, sare, usturoi",
    nutritionLabel: "Highly appetizing chickpea spread with healthy monounsaturated sesame and olive oils.",
    costPerProteinGram: 4.49 / (4.8 * 2.5),
    costPerCalorie: 4.49 / (166 * 2.5),
    healthScore: 80,
    image: "🥣",
    alternatives: ["Tofu Clasic în saramură (Classic Tofu)", "Unt de arahide cremos (Peanut Butter)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002005082",
    name: "Semințe de chia crude (Raw Chia Seeds)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 5.99,
    weight: "250g",
    protein: 16.5,
    carbs: 42.1,
    fat: 30.7,
    calories: 486,
    fiber: 34.4,
    sugar: 0.8,
    sodium: 0.01,
    ingredients: "100% semințe crude de chia (Salvia hispanica)",
    nutritionLabel: "High in fiber, calcium, iron, and antioxidant plant Omega-3 fatty acids.",
    costPerProteinGram: 5.99 / (16.5 * 2.5),
    costPerCalorie: 5.99 / (486 * 2.5),
    healthScore: 96,
    image: "🥜",
    alternatives: ["Miez de nucă crud (Raw Walnuts)", "Migdale crude (Raw Almonds)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002005099",
    name: "Semințe de dovleac crude decojite (Raw Pumpkin Seeds)",
    brand: "Crownfield",
    store: "Lidl",
    price: 7.99,
    weight: "200g",
    protein: 30,
    carbs: 10.7,
    fat: 49,
    calories: 559,
    fiber: 6.0,
    sugar: 1.0,
    sodium: 0.01,
    ingredients: "100% semințe decojite de dovleac crude",
    nutritionLabel: "Elite natural zinc and magnesium booster. Packed with plant protein and healthy fats.",
    costPerProteinGram: 7.99 / (30 * 2),
    costPerCalorie: 7.99 / (559 * 2),
    healthScore: 94,
    image: "🥜",
    alternatives: ["Miez de nucă crud (Raw Walnuts)", "Semințe de chia crude (Raw Chia Seeds)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002005105",
    name: "Ciocolată neagră premium 85% cacao (Premium Dark Chocolate)",
    brand: "J.D. Gross",
    store: "Lidl",
    price: 6.49,
    weight: "125g",
    protein: 8.5,
    carbs: 19.0,
    fat: 46.0,
    calories: 575,
    fiber: 11.2,
    sugar: 11.0,
    sodium: 0.02,
    ingredients: "Masă de cacao, unt de cacao, cacao pudră, zahăr, vanilie",
    nutritionLabel: "Elite anti-inflammatory snack. Highly rich in flavonoids and essential minerals.",
    costPerProteinGram: 6.49 / (8.5 * 1.25),
    costPerCalorie: 6.49 / (575 * 1.25),
    healthScore: 82,
    image: "🍫",
    alternatives: ["Unt de arahide cremos (Peanut Butter)", "Miez de nucă crud (Raw Walnuts)"],
    category: "Fats & Nuts"
  },
  {
    id: "5941002005112",
    name: "Creatină Monohidrată Creapure (Creatine Monohydrate)",
    brand: "Myprotein",
    store: "Metro",
    price: 89.00,
    weight: "250g",
    protein: 100,
    carbs: 0,
    fat: 0,
    calories: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    ingredients: "100% creatină monohidrată pură",
    nutritionLabel: "Most clinically researched performance supplement. Boosts strength, lean muscle mass.",
    costPerProteinGram: 89.00 / 250,
    costPerCalorie: 999,
    healthScore: 95,
    image: "🥤",
    alternatives: ["Whey Protein Concentrate 80% (Myprotein)", "Baton proteic cu ciocolată (High Protein Bar)"],
    category: "Supplements"
  },
  {
    id: "5941002005129",
    name: "Baton proteic cu ciocolată 50% proteină (High Protein Bar)",
    brand: "K-Classic",
    store: "Kaufland",
    price: 4.99,
    weight: "50g",
    protein: 50,
    carbs: 23,
    fat: 8.2,
    calories: 360,
    fiber: 4.2,
    sugar: 1.5,
    sodium: 0.15,
    ingredients: "Amestec proteic (zer, lapte, soia), înveliș de ciocolată, îndulcitori",
    nutritionLabel: "High protein sweet craving substitute. Low sugar, high bioavailable muscle food.",
    costPerProteinGram: 4.99 / 25,
    costPerCalorie: 4.99 / 180,
    healthScore: 78,
    image: "🍫",
    alternatives: ["Whey Protein Concentrate 80% (Myprotein)", "Iaurt în stil islandez Skyr 0% (Icelandic Skyr)"],
    category: "Supplements"
  }
];

export function getProductById(barcode: string): FoodProduct | undefined {
  return FOOD_DATABASE.find(p => p.id === barcode);
}

export function searchProducts(query: string): FoodProduct[] {
  const q = query.toLowerCase();
  return FOOD_DATABASE.filter(p => 
    p.name.toLowerCase().includes(q) || 
    p.brand.toLowerCase().includes(q) ||
    p.store.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  );
}
